### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by Fannangir** [itairaz1/israeli-bank-firefly-importer-hass-addon#1]
Hi,
I see the following error in the log when I start the addon:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-06-13 22:29:28.338] INFO (110): Getting state from firefly...
[2023-06-13 22:29:28.448] ERROR (110): Fatal error
    err: {
      "message": "Request failed with status code 404",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 404
              at settle (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/core/settle.js:19:12)
              at IncomingMessage.handleStreamEnd (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/adapters/http.js:570:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1359:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Authorization": "Bearer
          "User-Agent": "axios/1.4.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "http://192.168.1.186:6182",
        "method": "get",
        "url": "/api/v1/preferences/israeli-bank-importer"
      },
      "code": "ERR_BAD_REQUEST",
      "status": 404
    }
[2023-06-13 22:29:28.450] INFO (110): Running with cron
    cron: "0 6 * * *"

I have removed the token.
I have checked the URL, it is correct.
What am I missing?

Thanks.

**Comment by itairaz1** [comment]
Seemed to be like an old bug that wasn't fixed yet.
Until I will fix it, you can workaround it like mentioned in this comment https://github.com/itairaz1/israeli-bank-firefly-importer/issues/21#issuecomment-1427565126
Thank you for reporting

**Comment by itairaz1** [comment]
Fixed in 1.3.5
Please reopen if you have the same issue

**Comment by Fannangir** [comment]
@itairaz1 thank you very much for the quick overview.
Unfortunately, I still see the same error following 1.3.5 update.

Log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-06-14 08:35:03.378] INFO (110): Getting state from firefly...
[2023-06-14 08:35:03.484] ERROR (110): Fatal error
    err: {
      "message": "Request failed with status code 404",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 404
              at settle (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/core/settle.js:19:12)
              at IncomingMessage.handleStreamEnd (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/adapters/http.js:570:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1359:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Authorization": "Bearer eyJ0e.......",
          "User-Agent": "axios/1.4.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "http://192.168.1.186:6182",
        "method": "get",
        "url": "/api/v1/preferences/israeli-bank-importer"
      },
      "code": "ERR_BAD_REQUEST",
      "status": 404
    }
[2023-06-14 08:35:03.486] INFO (110): Running with cron
    cron: "0 6 * * *"

**Comment by itairaz1** [comment]
Do you have an option to rebuild the addon?
![image](https://github.com/itairaz1/israeli-bank-firefly-importer-hass-addon/assets/6906194/7d8f7550-e29e-4c04-92a4-fda7896f1841)

**Comment by Fannangir** [comment]
Great tip, there is a progress.
Now I see the following log:
* Replaced credit card and date numbers with XXXX.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-06-14 10:48:54.351] INFO (110): Getting state from firefly...
[2023-06-14 10:48:54.456] INFO (110): Getting scrap data...
[2023-06-14 10:53:25.811] INFO (110): Getting or creating accounts...
[2023-06-14 10:53:34.552] ERROR (110): Fatal error
    err: {
      "message": "Request failed with status code 422",
      "name": "AxiosError",
      "stack":
          AxiosError: Request failed with status code 422
              at settle (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/core/settle.js:19:12)
              at IncomingMessage.handleStreamEnd (file:///usr/local/lib/node_modules/israeli-bank-firefly-importer/node_modules/axios/lib/adapters/http.js:570:11)
              at IncomingMessage.emit (node:events:525:35)
              at endReadableNT (node:internal/streams/readable:1359:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/json",
          "Authorization": "Bearer eyJ...",
          "User-Agent": "axios/1.4.0",
          "Content-Length": "148",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "http://192.168.1.186:6182",
        "method": "post",
        "url": "/api/v1/accounts",
        "data": "{\"name\":\"XXXX\",\"account_number\":\"XXXX\",\"type\":\"asset\",\"account_role\":\"ccAsset\",\"credit_card_type\":\"monthlyFull\",\"monthly_payment_date\":\"XXXX-XX-XX\"}"
      },
      "code": "ERR_BAD_REQUEST",
      "status": 422
    }
[2023-06-14 10:53:34.554] INFO (110): Running with cron
    cron: "0 6 * * *"

**Comment by itairaz1** [comment]
It fails when trying to create an account in firefly. 
I will add log with the returned error, next version for better understanding the issue.
Meanwhile, which bank / credit card company are you using?
Do you see any irregular or malformed input in the `data`:
 ```
"data": "{"name":"XXXX","account_number":"XXXX","type":"asset","account_role":"ccAsset","credit_card_type":"monthlyFull","monthly_payment_date":"XXXX-XX-XX"}"
```

**Comment by itairaz1** [comment]
Just released 1.3.6 with additional logs. Please try it and paste the new logs (if needed, please rebuild)

**Comment by Fannangir** [comment]
You are amazing.
I have restarted 1.3.5, and it worked.
I have updated to 1.3.6, rebuilt, and it works as well.
A question before we can close the issue.
I see the following in firefly:
![IMG_2326](https://github.com/itairaz1/israeli-bank-firefly-importer-hass-addon/assets/30548574/419d28c2-2e67-4f1c-8963-560f78108292)
And the following in the log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-06-14 22:58:57.993] INFO (110): Starting Israeli Bank Firefly iii Importer
    version: "1.3.6"
[2023-06-14 22:58:57.994] INFO (110): Getting state from firefly...
[2023-06-14 22:58:58.088] INFO (110): Getting scrap data...
[2023-06-14 22:59:40.358] INFO (110): Getting or creating accounts...
[2023-06-14 22:59:40.480] INFO (110): Manipulating...
[2023-06-14 22:59:40.499] INFO (110): Getting firefly transactions to compare...
    since: "2023-04-02"
[2023-06-14 22:59:42.415] INFO (110): Creating transactions to firefly...
    count: 0
[2023-06-14 22:59:42.415] INFO (110): Updating transactions types to firefly...
count: 0
[2023-06-14 22:59:42.519] INFO (110): Updating last import...
[2023-06-14 22:59:43.244] INFO (110): Done.
[2023-06-14 22:59:43.244] INFO (110): Running with cron
    cron: "0 6 * * *"
    
Which means that it has successfully scraped all 4 credit cards, but I don’t see any info from Bank Leumi (עובר ושב / שוטף).
Is there something I have to add/modify in the configuration or in firefly?

Thank you very much for your great work and quick support.

**Comment by itairaz1** [comment]
It should basically work. There is nothing wrong in the log and it seemed like it successfully scrap.
Do you have multiple accounts in Leumi?
Try turn on debug log, by setting
```
log:
  level: debug
```
in the config.yaml file
and look for Leumi scrapings log, and see if there is something unusual.
You can post here, but make sure you omit sensitive data

**Comment by Fannangir** [comment]
I have 1 account in Leumi.
I have 2 isracard cards.
I have tried to include only 1 card in yaml, and tried both, same result, seems like both are scrapped (a general note which might lead to something).

According to my understanding of the logs, it seems like it does scrap leumi balance, but does not show in firefly.
Log (changed sensitive data to XXXXXX):

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-06-15 21:22:04.812] DEBUG (110): Config file '/config/israeli-bank-firefly-importer/config.yaml' loaded.
[2023-06-15 21:22:04.832] INFO (110): Starting Israeli Bank Firefly iii Importer
    version: "1.3.6"
[2023-06-15 21:22:04.833] INFO (110): Getting state from firefly...
[2023-06-15 21:22:04.945] INFO (110): Getting scrap data...
[2023-06-15 21:22:04.966] DEBUG (110): Scrapping...
    options: {
      "companyId": "leumi",
      "startDate": "2023-06-08T18:13:55.373Z",
      "args": [],
      "combineInstallments": false,
      "showBrowser": false,
      "outputData": {
        "enableTransactionsFilterByDate": false
      },
      "additionalTransactionInformation": true
    }
[2023-06-15 21:22:04.974] DEBUG (110): Scrapping...
    options: {
      "companyId": "isracard",
      "startDate": "2023-06-08T18:13:55.373Z",
      "args": [],
      "combineInstallments": false,
      "showBrowser": false,
      "outputData": {
        "enableTransactionsFilterByDate": false
      },
      "additionalTransactionInformation": true
    }
[2023-06-15 21:22:04.974] DEBUG (110): Scrapping...
    options: {
      "companyId": "visaCal",
      "startDate": "2023-06-08T18:13:55.373Z",
      "args": [],
      "combineInstallments": false,
      "showBrowser": false,
      "outputData": {
        "enableTransactionsFilterByDate": false
      },
      "additionalTransactionInformation": true
    }
[2023-06-15 21:22:04.975] DEBUG (110): Scrapping...
    options: {
      "companyId": "max",
      "startDate": "2023-06-08T18:13:55.373Z",
      "args": [],
      "combineInstallments": false,
      "showBrowser": false,
      "outputData": {
        "enableTransactionsFilterByDate": false
      },
      "additionalTransactionInformation": true
    }
[2023-06-15 21:22:46.771] DEBUG (110): Scrap result
    results: [
      {
        "success": true,
        "accounts": [
          {
            "accountNumber": "XXX-XXXXX_XX",
            "balance": XXXXXX.XX,
            "txCount": 2
          }
        ]
      },
      {
        "success": true,
        "accounts": [
          {
            "accountNumber": "1154",
            "txCount": 35
          },
          {
            "accountNumber": "0246",
            "txCount": 49
          }
        ]
      },
      {
        "success": true,
        "accounts": [
          {
            "accountNumber": "3067",
            "txCount": 1
          }
        ]
      },
      {
        "success": true,
        "accounts": [
          {
            "accountNumber": "4411",
            "txCount": 14
          }
        ]
      }
    ]
[2023-06-15 21:22:46.771] INFO (110): Getting or creating accounts...
[2023-06-15 21:22:46.891] INFO (110): Manipulating...
[2023-06-15 21:22:46.901] INFO (110): Getting firefly transactions to compare...
    since: "2023-04-02"
[2023-06-15 21:22:48.738] DEBUG (110): Got transactions from firefly
    numberOfTransactionsFromFirefly: 270
    since: "2023-04-02"
[2023-06-15 21:22:48.755] INFO (110): Creating transactions to firefly...
    count: 0
    toCreate: []
[2023-06-15 21:22:48.756] INFO (110): Updating transactions types to firefly...
    count: 0
    toTypeUpdate: []
[2023-06-15 21:22:48.869] INFO (110): Updating last import...
[2023-06-15 21:22:49.199] INFO (110): Done.
[2023-06-15 21:22:49.199] INFO (110): Running with cron
    cron: "0 6 * * *"

Do you see any clue?
Thanks again for your time.

**Comment by itairaz1** [comment]
Right, it seemed like it scrapped successfully. I think the account it is hidden in firefly, can you check if this is the case?

**Comment by Fannangir** [comment]
Are you referring to this setting?
![IMG_2574](https://github.com/itairaz1/israeli-bank-firefly-importer-hass-addon/assets/30548574/896bf3e7-68af-44fb-b860-62c94c93e6cd)

I guess this is correctly set up, or should there be additional Leumi row?

**Comment by itairaz1** [comment]
Check if it's here: /inactive-accounts/asset
Also, this account should be "Default asset accounts" and not "Saving accounts"

**Comment by Fannangir** [comment]
Nope, nothing there, unfortunately.
![IMG_2575](https://github.com/itairaz1/israeli-bank-firefly-importer-hass-addon/assets/30548574/53e37269-c635-4a36-a45f-36150de57d04)

Should it automatically create an account, or alternatively, should I create an account?
If I create one, how would the scrapped data connect to the correct asset?

Another option, maybe I can simply delete everything and start from scratch?
How would be the correct way to do it?

**Comment by itairaz1** [comment]
> Should it automatically create an account, or alternatively, should I create an account?
> If I create one, how would the scrapped data connect to the correct asset?

The system creates for you account and sets the account number, that's how it identified for next run. So you can check if the account was created with the account number

> Another option, maybe I can simply delete everything and start from scratch?
> How would be the correct way to do it?

Since the system stores config on firefly, and firefly doesn't have a UI to remove it, I suggest to re-install firefly

**Comment by Fannangir** [comment]
Wiped firefly, re-created the container and ran the scrapper.
The result is that I don’t have any Leumi account (savings isn’t available as well), got only my four credit cards.
![IMG_2647](https://github.com/itairaz1/israeli-bank-firefly-importer-hass-addon/assets/30548574/fc431c74-f459-44a6-8bed-63739d097dfd)

Nothing under inactive accounts.
And the currency became Euro.
I probably had to change the currency before running the scrapper.
Do you have any additional idea why Leumi isn’t seen?

**Comment by Fannangir** [comment]
I have made another test.
I have deleted Firefly again, and recreated the container.
I have deleted the credit cards from the scrapper config, left only Leumi bank information.
It seems like the scrapper does its job right from scrapping point of view, but it probably doesn't push the data correctly to firefly, as firefly does not show any new data from the scrap process.

The log from the scrapper (replaced the account number and the amount with XXX... The information is scrapped correctly):
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-07-15 21:09:10.276] DEBUG (111): Config file '/config/israeli-bank-firefly-importer/config.yaml' loaded.
[2023-07-15 21:09:10.280] INFO (111): Starting Israeli Bank Firefly iii Importer
    version: "1.3.7"
[2023-07-15 21:09:10.280] INFO (111): Getting state from firefly...
[2023-07-15 21:09:10.369] DEBUG (111): Firefly previous state not found (its ok if its first run), using empty object.
[2023-07-15 21:09:10.369] INFO (111): Getting scrap data...
[2023-07-15 21:09:10.376] DEBUG (111): Scrapping...
    options: {
      "companyId": "leumi",
      "startDate": "2018-07-15T18:09:10.370Z",
      "args": [],
      "combineInstallments": false,
      "showBrowser": false,
      "outputData": {
        "enableTransactionsFilterByDate": false
      },
      "additionalTransactionInformation": true
    }
[2023-07-15 21:09:41.146] DEBUG (111): Scrap result
    results: [
      {
        "success": true,
        "accounts": [
          {
            "accountNumber": "XXX-XXXXX_XX",
            "balance": XXXXXX.XX,
            "txCount": XXX
          }
        ]
      }
    ]
[2023-07-15 21:09:41.147] INFO (111): Getting or creating accounts...
[2023-07-15 21:09:42.998] INFO (111): Manipulating...
[2023-07-15 21:09:42.999] INFO (111): Getting firefly transactions to compare...
    since: "2023-07-14"
[2023-07-15 21:09:43.084] DEBUG (111): Got transactions from firefly
    numberOfTransactionsFromFirefly: 1
    since: "2023-07-14"
[2023-07-15 21:09:43.084] INFO (111): Creating transactions to firefly...
    count: 0
    toCreate: []
[2023-07-15 21:09:43.084] INFO (111): Updating transactions types to firefly...
    count: 0
    toTypeUpdate: []
[2023-07-15 21:09:43.162] INFO (111): Updating last import...
[2023-07-15 21:09:43.760] INFO (111): Done.
[2023-07-15 21:09:43.760] INFO (111): Running with cron
    cron: "0 6 * * *"

**Comment by itairaz1** [comment]
Which firefly iii version do you use?

**Comment by Fannangir** [comment]
6.0.19.
I believe it is the latest available.

**Comment by itairaz1** [comment]
OK, I planning to add an option to reset firefly state, it might help. I will update here when it's ready

**Comment by Fannangir** [comment]
Thank you very much for the effort.

Meanwhile, I was thinking to replace the HA add-on with a docker container.
Is there any difference between the two which might solve the issue?
